spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
#  sql:
#    init:
#      mode:
#      schema-locations: classpath:h2/schema.sql
#      data-locations: classpath:h2/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update